### ISSUE TITLE
Considerações do 03

### ISSUE THREAD

**Issue by JulianaAmoasei** [rfukui/do-excel-ao-sistema-complexo#1]
Escrever uma explicação sobre o que são migrations e por que são necessárias (não esquecer do up e down)

Os models estão todos criados no singular mas o de livros vc criou como "books". Vou deixar no singular para manter o padrão

Depois que cria as associações, ficou faltando explicação também (conceito de 1 autor para N livros, N livros para 1 editora, etc)

Na parte de criar o arquivo de migrações dos livros na mão, vc já criou com as references. Eu tirei essas linhas, porque vc adiciona elas logo abaixo, quando faz as associações.

Explicar o que são serviços e por que estamos criando isso

Explicar o que são controladores e por que estamos criando

Explicar o que são utils e por que estamos criando. Essa parte da utils ficou especialmente confusa

Diferença de testes de integração para testes unitários

Talvez seja melhor repensar essa parte dos testes, pois o tutorial não falou nada de rotas ainda e precisa dessa parte pro teste fazer sentido

A parte de test no docker-compose é pra ser criada dentro de services né? Fiz uma correçãozinha no tutorial para mostrar isso

**Comment by rfukui** [comment]
Solved
